### ISSUE TITLE
Downloaded libs are deleted and dowloaded all over again when deleting "build" directory

### ISSUE THREAD

**Issue by plywood98** [JanWilczek/audio-plugin-template#10]
The way the libraries get downloaded from github seems super useful, however I do not understand why removing the build directory (the one created when compiling) appears to have cmake download the library all over again. To reproduce:
- compile
- remove the "build" directory: the libs/JUCE is still there
- the next run of cmake will scratch the libs/JUCE and redownload it

**Comment by JanWilczek** [comment]
I agree but this is a CPM issue, please, consider adding an issue there. Thanks!
