### ISSUE TITLE
Difficulty installing the project on Ubuntu 24.04

### ISSUE THREAD

**Issue by filipeborato** [JanWilczek/audio-plugin-template#8]
Good contribution. I made the installation in the crude system and I have some problems.

![image](https://github.com/JanWilczek/audio-plugin-template/assets/21025394/a49e95b0-f0c5-43bd-9075-656b503898a2)

The first problem I resolved by installing this package:
```
sudo apt-get install pkg-config
```
There were other libraries I needed to get:

```
sudo apt install libx11-dev && sudo apt install libxrandr-dev &&  sudo apt-get install libxinerama-dev && sudo apt install libxcursor-dev && sudo apt-get install libfontconfig1-dev
```
After that, I realized that I hadn't installed the Alsa library:
![image](https://github.com/JanWilczek/audio-plugin-template/assets/21025394/0cf1a835-3747-4ada-a2ac-30b9de53062f)

I fix the problem with two commands:
```
sudo apt-get -y install alsa-base
```
```
sudo apt-get install libasound2-dev
```

And it worked:

![image](https://github.com/JanWilczek/audio-plugin-template/assets/21025394/df2f6e2a-d4f7-4b13-ad2d-609e6ef327c3)

**Comment by JanWilczek** [comment]
JUCE provides a full list of Linux dependencies here: https://github.com/juce-framework/JUCE/blob/master/docs/Linux%20Dependencies.md
